version: '3.9'

services:
  rest:
    build: ./rest
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    working_dir: /app
    command: python rest_api.py

  soap:
    build: ./soap
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data
    working_dir: /app
    command: python soap_server.py

  graphql:
    build: ./graphql
    ports:
      - "5002:5002"
    volumes:
      - ./data:/data
    working_dir: /app
    command: python graphqlapi_server.py

  grpc:
    build: ./grpc
    ports:
      - "5003:5003"
    volumes:
      - ./data:/data
    working_dir: /app
    command: python grpc_server.py
